In [2]:
import numpy as np
matrix1 = np.random.randint(1,101, size=(4,4))

In [3]:
print(matrix1)

[[33 35 75 16]
 [65 85 78 82]
 [57 87 29 36]
 [13 53 56 90]]


In [4]:
np.sum(matrix1)

np.int64(890)

In [5]:
np.min(matrix1)

np.int64(13)

In [6]:
np.max(matrix1)

np.int64(90)

In [7]:
matrix1[matrix1%2 == 0] = 0

In [8]:
print(matrix1)

[[33 35 75  0]
 [65 85  0  0]
 [57 87 29  0]
 [13 53  0  0]]


In [9]:
np.sum(matrix1, axis=1)

array([143, 150, 173,  66])

In [10]:
np.transpose(matrix1)

array([[33, 65, 57, 13],
       [35, 85, 87, 53],
       [75,  0, 29,  0],
       [ 0,  0,  0,  0]])

In [43]:
result = matrix1 + 5

In [44]:
print(result)

[[38 40 80  5]
 [70 90  5  5]
 [62 92 34  5]
 [18 58  5  5]]


In [53]:
arr1 = np.array([1,2,3,4])
sub_matrix = result - arr1

In [54]:
print(sub_matrix)

[[37 38 77  1]
 [69 88  2  1]
 [61 90 31  1]
 [17 56  2  1]]


In [55]:
arr2 = np.array([[1],[2],[3],[4]])
mult_matrix = sub_matrix * arr2

In [56]:
print(mult_matrix)

[[ 37  38  77   1]
 [138 176   4   2]
 [183 270  93   3]
 [ 68 224   8   4]]


In [57]:
arr3 = np.array([np.mean(mult_matrix[0]), np.mean(mult_matrix[1]), np.mean(mult_matrix[2]), np.mean(mult_matrix[3])])
sub_matrix2 = mult_matrix - arr3

In [58]:
print(sub_matrix2)

[[  -1.25  -42.    -60.25  -75.  ]
 [  99.75   96.   -133.25  -74.  ]
 [ 144.75  190.    -44.25  -73.  ]
 [  29.75  144.   -129.25  -72.  ]]
