In [3]:
import numpy as np
matrix1 = np.random.randint(1,101, size=(4,4))

In [4]:
print(matrix1)

[[49 19 36 99]
 [73 53 93 46]
 [13 58 18 76]
 [61 90 91 70]]


In [5]:
np.sum(matrix1)

np.int64(945)

In [7]:
np.min(matrix1)

np.int64(13)

In [8]:
np.max(matrix1)

np.int64(99)

In [9]:
matrix1[matrix1%2 == 0] = 0

In [10]:
print(matrix1)

[[49 19  0 99]
 [73 53 93  0]
 [13  0  0  0]
 [61  0 91  0]]


In [11]:
np.sum(matrix1, axis=1)

array([167, 219,  13, 152])

In [13]:
np.transpose(matrix1)

array([[49, 73, 13, 61],
       [19, 53,  0,  0],
       [ 0, 93,  0, 91],
       [99,  0,  0,  0]])